SELECT CHILDREN.ID, CHILDREN.GENOTYPE, PARENT.GENOTYPE parent_genotype
FROM ECOLI_DATA CHILDREN JOIN ECOLI_DATA PARENT ON CHILDREN.PARENT_ID = PARENT.ID
WHERE (CHILDREN.GENOTYPE & PARENT.GENOTYPE) = PARENT.GENOTYPE
ORDER BY CHILDREN.ID ASC